version: '3.8'

services:
  stable-client:
    container_name: stable-client-container
    build:
      context: .
      dockerfile: Dockerfile
      target: prod_im
    image: stl_prod
    ports:
      - "5001:5001"
      - "5173:5173"
    volumes:
      - .:/app
    depends_on:
      - pgsql
    command: "npm run start:server"
    mem_limit: 512m
    cpus: 0.5

  pgsql:
    container_name: pgsql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stl
    volumes:
      - ./data:/var/lib/postgresql/data


  